spring:
  data:
      mongodb:
        uri: mongodb+srv://app_user:appuser#$4321@cluster1.hxqladc.mongodb.net/contract?retryWrites=true&w=majority

server:
  port: 8081
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG